### ISSUE TITLE
Deprecated call to POST /rest/system/config (DEPRECATED)

### ISSUE THREAD

**Issue by N07070** [triplepoint/ansible-syncthing#1]
Per [docs](https://docs.syncthing.net/rest/system-config-post.html) at this https://github.com/triplepoint/ansible-syncthing/blob/main/tasks/_ensure_config.yml#L56  line, the task should be changed. 

As of today, even if the config is well applied, the server doesn't return anything. That, in turns makes curl return a code 52, which per [curl's man page](https://www.man7.org/linux/man-pages/man1/curl.1.html) will be an error, and thus halt execution of the playbook.

See https://docs.syncthing.net/rest/config.html for the new endpoints. 

Thanks a lot :)

**Comment by triplepoint** [comment]
Hi there, sorry for the delay in answering.
This commit https://github.com/triplepoint/ansible-syncthing/commit/a1c6adde0f3e0ed5aa00dcd97cfb11b580d61563 should address this issue.  I moved to the new endpoints for config, and simplified the logic for setting up the GUI username and password by calling the CLI commands instead of using CURL calls.

A backwards incompatible change is that you need to specify the api key in your inventory variables, instead of relying on the auto-generated one syncthing would've already had in place.  See the change in the defaults/main.yml for the variable you need to override.

Thanks for the interest.
